### ISSUE TITLE
Trouble getting it installed trough pip

### ISSUE THREAD

**Issue by skipadi** [afcmrp/python-mfiles#1]
Hey, 

having trouble getting this installed trough pip in pycharm or in cmd pip. 
Complains module not found and only gets some 1kb text files on install.

If you can help me fix it or fix the issue, it would be greatly appreciated :)

**Comment by afcmrp** [comment]
Thanks for the heads up! Managed to mess up the package structure and it took me this long to realize it... Updated accordingly and it should work for the newest version (0.4.1).
