### ISSUE TITLE
Problem with the Cookie

### ISSUE THREAD

**Issue by barbyware** [afcmrp/python-mfiles#8]
m-files fails with call from python because the m-file python wrapper do not past the session cookies to the requests

**Comment by afcmrp** [comment]
Interesting, could you elaborate a bit more? I can't find any mention of session cookie in the M-Files REST API reference. Do you mean that the authentication header is not set? If so, a likely cause is that either user, pass, vault guid or server are not set in the client, and therefore it doesn't perform the login request.

**Comment by afcmrp** [comment]
Thanks for helping out, PR merged and PyPI package updated. :)
